#!/bin/sh
#
# Copyright (c) 2013 Ashley Diamond.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# Concepts taken from pc-bsd equivalent
#

# PROVIDE: imgbsdinit_early
# BEFORE: netif
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="imgbsdinit_early"
rcvar="imgbsdinit_early_enable"

stop_cmd="imgbsdinit_stop"
start_cmd="imgbsdinit_start"

load_rc_config $name

: ${imgbsdinit_early_enable=NO}

imgbsdinit_start() {

	# Make sure imgBSD Directories exist
	if [ -e "/home/.system" ] ; then
		mkdir -p /home/.system
		mkdir -p /home/.system/var_db
		mkdir -p /home/.system/pbi
	fi

	# Scan for network interfaces
	/usr/share/scripts/interfaceFinder.sh > /dev/null 2>&1
}

imgbsdinit_stop() {
	echo "Nothing to stop."
}

run_rc_command "$1"
