#!/bin/sh
#
# Copyright (c) 2013 Ashley Diamond.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# Concepts taken from pc-bsd equivalent
#

# PROVIDE: imgbsdinit_late
# BEFORE: LOGIN
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="imgbsdinit_late"
rcvar="imgbsdinit_late_enable"

stop_cmd="imgbsdinit_stop"
start_cmd="imgbsdinit_start"

load_rc_config $name

: ${imgbsdinit_late_enable=NO}

imgbsdinit_start() {

	# If this is the first boot then save the generated ssh data
	( sleep 5; ls -la /home/* > /dev/null 2>&1 || \
		cfg ssh >/dev/null 2>/dev/null ) &

	# Change Xorg priority
	( sleep 5; rtprio 31 -`pgrep Xorg` > /dev/null 2>&1) &
}

imgbsdinit_stop() {
	echo "Nothing to stop."
}

run_rc_command "$1"
