#!/bin/sh
#
# Copyright (c) 2013 Ashley Diamond.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

set -e
set -u

. /usr/share/scripts/img_update-functions.sh

usage() {
	echo "	network	- automated network update"
	echo "	local 	- upgrade from file <local of image>"
	echo "	switch 	- boot into other image, useful when just changing loader.conf"
	echo "	recover	- Booting a new image has failed and you wish to go back"
	echo "	info 	- show partition info"
	exit 1
}

################################################################################

# Network update, ssh
networkUpdate() {
	set_partition_info
	unmount_target
	check_for_update
	get_disk_image
	ensure_current_part_is_active_part
	perform_system_upgrade "${IMG_DIR}/${IMAGE_VERSION}" || die "Couldn't update image"
	set_active_partition "$TARGET_PARTITION_NUM" "$DRIVE"
	store_update_info
}

updateFromLocalFile() {
	[ -e "$IMG_FILE" ] || die "Image $IMG_FILE could not be found"
	set_partition_info
	unmount_target
	ensure_current_part_is_active_part
	perform_system_upgrade "$IMG_FILE"
	set_active_partition "$TARGET_PARTITION_NUM" "$DRIVE"
	store_update_info
}

# Switch boot partitions and copy overlays
switchBootPartition() {
	set_partition_info
	unmount_target
	set_active_partition "$TARGET_PARTITION_NUM" "$DRIVE"
}

showInfo() {
	set_partition_info
	print_partition_info
	exit 0
}

################################################################################

MNT_DIR="/tmp/MNT.$$"
IMG_DIR="/tmp/.OS_UPDATE"
OVERLAY_DIR="/home/.system/overlay"

am_i_root

timer start || true

if [ $# -eq 0 ]; then
	echo "You entered no options"
	usage
fi

case $1 in
	network) networkUpdate;;
	local) export IMG_FILE="$2"; updateFromLocalFile;;
	switch) switchBootPartition;;
	recover) switchBootPartition;;
	info) showInfo;;
	*) echo "input not recognised"; usage;;
esac

timer stop || true
[ -e "$MNT_DIR" ] && rm -rf $MNT_DIR || true
echo "SUCCESS!"

exit 0
